language: node_js
node_js:
  - "10"

dist: trusty
sudo: false

cache:
  directories:
     - ./weather-app/node_modules

before_install: cd weather-app

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
