language: node_js
node_js:
  - "10"

dist: trusty
sudo: false

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - cd weather-app
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
