language: node_js
node_js:
  - "10"

dist: trusty
sudo: false

os: windows

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - bundle exec rake
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
